version: '3.3'

services:
  django:
    build:
      context: ../
      dockerfile: docker/BackendDockerfile      
    container_name: docker-django-vue-backend  
    volumes:
      - .:/app
    ports:
      - "8002:8000"
  vue:
    build:
      context: ../
      dockerfile: docker/FrontendDockerfile
    container_name: docker-django-vue-frontend
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    depends_on: 
      - django